### ISSUE TITLE
Package will not be found on kinetic

### ISSUE THREAD

**Issue by billyjov** [gnoliyil/pr2_kinetic_packages#1]
I tried to install it by creating new package and got following error 
`ERROR: dependency [pr2_controllers_msgs] cannot be found`

**Comment by billyjov** [comment]
I solved it using `control_msgs` instead of `pr2_controllers_msgs`

**Comment by gnoliyil** [comment]
This compilation error can be solved by compiling only the "pr2_controllers_msgs" package first: 
```
> catkin_make --pkg pr2_controllers_msgs
```
Then you can run the `catkin_make` command again: 
```
> catkin_make
```

**Comment by billyjov** [comment]
Alright, thanks for the tip.
